import "dotenv/config";
import http from "node:http";
import {CompanyMemory} from "./core/memory.js";
import {runCeoCycle} from "./agents/ceo.js";
import type {CompanyState} from "./core/types.js";
const port=Number(process.env.PORT||3000),memory=new CompanyMemory();
let state:CompanyState={cashChf:Number(process.env.STARTING_CAPITAL_CHF||100),revenueChf:0,costsChf:0,customers:0,visitors:0,conversionRate:0,cycle:0};
function page(){const d=memory.getDecisions(),o=memory.getOpportunities();const cards='<div class="grid"><div class="card"><small>Cash</small><h2>CHF '+state.cashChf.toFixed(2)+'</h2></div><div class="card"><small>Revenue</small><h2>CHF '+state.revenueChf.toFixed(2)+'</h2></div><div class="card"><small>Costs</small><h2>CHF '+state.costsChf.toFixed(2)+'</h2></div><div class="card"><small>Cycle</small><h2>'+state.cycle+'</h2></div></div>';const opps=o.slice(0,5).map(x=>'<p><b>'+x.score+'/100</b> — '+x.solution+'<br><small>'+x.targetCustomer+' · MVP '+x.estimatedMvpDays+'d · CHF '+x.estimatedMvpCostChf+'</small></p>').join('')||'<p>No research run yet.</p>';const decs=d.slice(0,10).map(x=>'<p><b>'+x.agent+'</b> — '+x.action+'<br><small>'+x.reason+'</small></p>').join('')||'<p>No decisions yet.</p>';return '<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Autonomous Company v0.1</title><style>body{font-family:system-ui;margin:0;background:#0b0d10;color:#f5f7fa}main{max-width:1000px;margin:40px auto;padding:20px}.grid{display:grid;grid-template-columns:repeat(4,1fr);gap:12px}.card{background:#151922;border:1px solid #252b36;border-radius:14px;padding:18px}button{padding:12px 16px;border:0;border-radius:10px;cursor:pointer}small{color:#9aa4b2}@media(max-width:700px){.grid{grid-template-columns:1fr 1fr}}</style></head><body><main><h1>Autonomous Company <small>v0.1</small></h1><p>Closed-loop AI business control system — safe by default.</p>'+cards+'<form method="post" action="/cycle" style="margin:20px 0"><button>Run CEO cycle</button></form><div class="card"><h2>Top opportunities</h2>'+opps+'</div><div class="card"><h2>Decision ledger</h2>'+decs+'</div></main></body></html>'}
const server=http.createServer((req,res)=>{if(req.method==="POST"&&req.url==="/cycle"){state.cycle++;const decision=runCeoCycle(state,memory);state.costsChf+=decision.costChf;state.cashChf-=decision.costChf;res.writeHead(303,{Location:"/"});res.end();return}if(req.method==="GET"&&req.url==="/api/state"){res.writeHead(200,{"Content-Type":"application/json"});res.end(JSON.stringify({state,decisions:memory.getDecisions(),opportunities:memory.getOpportunities()}));return}res.writeHead(200,{"Content-Type":"text/html; charset=utf-8"});res.end(page())});
server.listen(port,()=>console.log("Autonomous Company v0.1 running on http://localhost:"+port));
